// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedTyping.Model.Data;

namespace SpeedTyping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211031061732_AddedForeignKeyToTextTypesInfo")]
    partial class AddedForeignKeyToTextTypesInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "dc086066-451d-4cb1-a1ad-933352eb82b4",
                            ConcurrencyStamp = "fecb613a-37ab-4368-845b-509d7c9db1a4",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d4dad604-45e4-4ee7-b7b1-697bf7a623b2",
                            ConcurrencyStamp = "12a9882d-b303-4837-b879-b23c4365a049",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "215eedc8-7e86-46f6-88dc-6b052c4ed7b0",
                            RoleId = "dc086066-451d-4cb1-a1ad-933352eb82b4"
                        },
                        new
                        {
                            UserId = "f294e833-15e9-4066-8b41-61847ff6f0f7",
                            RoleId = "d4dad604-45e4-4ee7-b7b1-697bf7a623b2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TextWriteTypesInfoId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TextWriteTypesInfoId");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "215eedc8-7e86-46f6-88dc-6b052c4ed7b0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "979ffff9-2573-4f62-9296-6e4d2b930fc6",
                            Email = "zenoteper@icloud.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZENOTEPER@ICLOUD.COM",
                            NormalizedUserName = "MATVEY",
                            PasswordHash = "AQAAAAEAACcQAAAAEF2wrL6lH3IJ1FXS48CVmy0ILs/PcNqFJLDiTLVX0rNrttMh4cNNyViOTGNPLbB7nw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TextWriteTypesInfoId = 0,
                            TwoFactorEnabled = false,
                            UserName = "Matvey"
                        },
                        new
                        {
                            Id = "f294e833-15e9-4066-8b41-61847ff6f0f7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6429d67a-062f-4960-808b-3366e82e915f",
                            Email = "someuser@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SOMEUSER@EMAIL.COM",
                            NormalizedUserName = "SOMEUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEJC1dfSaVs2F7B3D0v8NONvpvrWJ1N9gspVC+DaR7k8mVZBIqBg4QHOWNHeH3lff8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TextWriteTypesInfoId = 0,
                            TwoFactorEnabled = false,
                            UserName = "someUser"
                        });
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.TextWriteInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<int>("CorrectCharsCount")
                        .HasColumnType("int");

                    b.Property<int>("ErrorCharsCount")
                        .HasColumnType("int");

                    b.Property<int>("Miliseconds")
                        .HasColumnType("int");

                    b.Property<int>("TextId")
                        .HasColumnType("int");

                    b.Property<int>("TextSize")
                        .HasColumnType("int");

                    b.Property<int>("TextWriteType")
                        .HasColumnType("int");

                    b.Property<int?>("TextWriteTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UnfixedErrorsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TextWriteTypeId");

                    b.ToTable("TextWriteInfo");
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.TextWriteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TextWriteTypeInfosId")
                        .HasColumnType("int");

                    b.Property<int>("TypeInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TextWriteTypeInfosId");

                    b.ToTable("TextWriteType");
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.TextWriteTypeInfos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("TextWriteTypes");
                });

            modelBuilder.Entity("SpeedTyping.Model.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SpeedTyping.Model.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SpeedTyping.Model.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpeedTyping.Model.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SpeedTyping.Model.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.ApplicationUser", b =>
                {
                    b.HasOne("SpeedTyping.Model.Data.TextWriteTypeInfos", "TextWriteTypesInfo")
                        .WithMany()
                        .HasForeignKey("TextWriteTypesInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TextWriteTypesInfo");
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.TextWriteInfo", b =>
                {
                    b.HasOne("SpeedTyping.Model.Data.TextWriteType", null)
                        .WithMany("TextWriteInfos")
                        .HasForeignKey("TextWriteTypeId");
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.TextWriteType", b =>
                {
                    b.HasOne("SpeedTyping.Model.Data.TextWriteTypeInfos", null)
                        .WithMany("TypesInfoList")
                        .HasForeignKey("TextWriteTypeInfosId");
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.TextWriteType", b =>
                {
                    b.Navigation("TextWriteInfos");
                });

            modelBuilder.Entity("SpeedTyping.Model.Data.TextWriteTypeInfos", b =>
                {
                    b.Navigation("TypesInfoList");
                });
#pragma warning restore 612, 618
        }
    }
}
